services:
  agent-workcell-base:
    build:
      context: .
      dockerfile: sandbox/dockerfiles/base.Dockerfile
    image: local/agent-workcell-base

  agent-workcell-pi:
    build:
      context: sandbox/
      dockerfile: dockerfiles/pi.Dockerfile
    image: local/agent-workcell-pi
    depends_on:
      - agent-workcell-base

  agent-workcell-opencode:
    build:
      context: sandbox/
      dockerfile: dockerfiles/opencode.Dockerfile
    image: local/agent-workcell-opencode
    depends_on:
      - agent-workcell-base

  agent-workcell-codex:
    build:
      context: sandbox/
      dockerfile: dockerfiles/codex.Dockerfile
    image: local/agent-workcell-codex
    depends_on:
      - agent-workcell-base

  agent-workcell-claude:
    build:
      context: sandbox/
      dockerfile: dockerfiles/claude.Dockerfile
    image: local/agent-workcell-claude
    depends_on:
      - agent-workcell-base
